spring:
  application:
    name: Echohub

  banner:
    location: classpath:logo.txt

  data:
    mongodb:
      uri: mongodb://localhost:27017/echohub
  security:
    user:
      name: sahil
      password: admin

  doc:
    swagger-ui:
      path: /swagger-ui.html

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8080

#supported units  -- miliseconds seconds minutes hours days
#vidorbit:
#  token:
#    access:
#      secret: H2zMNUhuL4lOxe1VorcWJTB36b23ZrPnA3PrLQD7YDw=
#      expiration: 30 minutes
#    refresh:
#      secret: CCLBhOPYmEl2AnhGBEmE8vCYDkuoKTX5UEaWuW6zRsU=
#      rotation_threshold: 15 minutes
#      expiration: 60 minutes

#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: shutdown
#  endpoint:
#    shutdown:
#      enabled: true
