spring:
  application:
    name: VidOrbit

  banner:
    location: classpath:logo.txt

  data:
    mongodb:
      uri: mongodb://localhost:27017/VidOrbit

  security:
    user:
      name: sahil
      password: admin

server:
  port: 8080
